use MASS;
CREATE TABLE users(
    id INT(11) NOT NULL,
    username VARCHAR(22) NOT NULL,
    password VARCHAR(200) NOT NULL,
    email VARCHAR(100) NOT NULL
);

ALTER TABLE users
    ADD PRIMARY KEY (id);

ALTER TABLE users
    MODIFY id INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 1;

ALTER TABLE users 
    ADD phoneNumber INT(11); 